---
- hosts: switches
  become: yes


  tasks:
    - name: Create Loopback1
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback1
            description: Created Loopback
            enabled: true
    