---
campus:
  children:
    switches:
      hosts:
        192.168.122.7[2-6]:
      vars:
        testVar: 999

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: brian
    ansible_ssh_pass: cisco